name: Release

on:
  workflow_dispatch:
  release:
    types: [published]

env:
  COMPONENT_DIR: repo

jobs:
  release_zip_file:
    name: Prepare release asset
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
      - name: Update manifest.json version to ${{ github.event.release.tag_name }}
        run: |
          python3 ${{ github.workspace }}/.github/scripts/update_hacs_manifest.py --version ${{ github.event.release.tag_name }} --path /custom_components/repo/
      - name: Commit manifest update
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ./custom_components/repo/manifest.json
          git commit -m "Updated manifest.json"
          git push origin HEAD:main
      - name: Create zip
        run: |
          cd custom_components/repo
          zip repo.zip -r ./
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@2.9.0
        with:
          repo_token: ${{ secrets.PAT_TOKEN }}
          file: ./custom_components/repo/repo.zip
          asset_name: repo.zip
          tag: ${{ github.ref }}
          overwrite: true
