name: Sync labels

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
    paths:
      - https://raw.githubusercontent.com/UnoSite/files/refs/heads/main/sync-labels.yml
  workflow_dispatch:

jobs:
  labels:
    name: ♻️ Sync labels
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v4

      - name: 🚀 Run Label Syncer
        uses: micnncim/action-label-syncer@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          manifest: https://raw.githubusercontent.com/UnoSite/files/refs/heads/main/sync-labels.yml
